### ISSUE TITLE
Webrender broken in firefox

### ISSUE THREAD

**Issue by git-bruh** [danvd/wlroots-eglstreams#19] opened 2021-05-24 04:31 UTC
Hi, I'm running the latest NVIDIA drivers (465.27) with sway commit `12e223e7973f7d7132d95c6302328067dec732ce` built against wlroots-eglstreams `e46fce216e6854f8b98e0b6ed2ec725a045f9b6a`.

Enabling webrender (or `layers.acceleration.force-enabled`) in firefox just shows a transparent window, but it can respond to keypresses. Context menus can be opened by right-clicking aswell (probably because they're handled by GTK).

Logs with `sway --debug`:

Regular firefox: https://0x0.st/-egr.txt

Webrender firefox: http://0x0.st/-egs.txt

Screenshot (flipped for some reason): http://0x0.st/-egz.png

Thanks for your work on this :)�

**Comment by danvd** [comment] 2021-05-24 06:20
Hi @git-bruh,
Could you please provide more details:

1) Which site I can open to reproduce this?
2) Is MOZ_ENABLE_WAYLAND=1 environment var is defined?
3) Which version of firefox do you use?

Also please upgrade wlroots-eglstreams to the latest commit

**Comment by danvd** [comment] 2021-05-24 07:10
I tried this option with firefox 88.0.1 and everything seems to work fine. Though I tested only a subset of websites that I most commonly use.

**Comment by git-bruh** [comment] 2021-05-24 08:00
1. The issue happens right on startup, so you can't open any sites.

2. Yes, the variable is defined.

3. I'm using firefox 88.0.1 aswell. wlroots-eglstreams is the latest commit too.

Would you be able to check if i send you my firefox binary ? It might not work though, due to distro library incompatibilities.�

**Comment by danvd** [comment] 2021-05-24 13:06
Sure, I'll check it

**Comment by git-bruh** [comment] 2021-05-24 13:47
Here: https://github.com/git-bruh/test/releases/download/test/firefox.tar.xz

You should be able to just untar it and run `MOZ_WEBRENDER=1 ./firefox/firefox`�

**Comment by git-bruh** [comment] 2021-05-24 13:59
Ah sorry i forgot i build it with `-march=native` so it'll probably not work unless you have a ryzen cpu. You can close this issue since it works for you, I have a pretty weird setup so it's probably something on my side.�

**Comment by danvd** [comment] 2021-05-24 19:48
I was able to reproduce this! Don't know why it worked the first time, but now both setting flag and MOZ_WEBRENDER=1 lead to empty window. 
This looks strange - firefox doesn't show any errors. Will check what's happening.

**Comment by danvd** [comment] 2021-05-24 23:04
Looks like this is a known issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1646135 unfortunately.
Lets wait until 470 driver release and see. This issue can be probably left opened.

**Comment by Sporif** [comment] 2021-06-22 10:22
An Nvidia dev has sent a patch: https://phabricator.services.mozilla.com/D118304.

I tried the [test build](https://treeherder.mozilla.org/jobs?repo=try&revision=92241491b8756bd639b9bf4fbc5ebe179ba81c7b) and it works.

**Comment by Sporif** [comment] 2021-08-11 13:25
The fix is now out with the release of Firefox 91.0

https://hg.mozilla.org/releases/mozilla-release/rev/c2191ee9cb6519c9736108ee1c82599a533ef552

**Comment by danvd** [comment] 2021-08-11 22:13
Closing this as resolved

**Closed by danvd** 2021-08-11 22:13 UTC
